#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');const pub=root;let checks=0,failures=[];const ok=(condition,message)=>{checks++;if(!condition)failures.push(message)};const files=[];const walk=dir=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);e.isDirectory()?walk(p):files.push(p)}};walk(root);
const bootstrap=fs.readFileSync(path.join(root,'app_private/bootstrap.php'),'utf8');const robots=fs.readFileSync(path.join(pub,'robots.txt'),'utf8');const sitemap=fs.readFileSync(path.join(pub,'sitemap.xml'),'utf8');
for(const token of ['canonical','og:title','twitter:card','application/ld+json','skip-link','favicon-48.png','apple-touch-icon.png','site.webmanifest'])ok(bootstrap.includes(token),`Shared header missing ${token}`);
for(const bot of ['Googlebot','Bingbot','OAI-SearchBot','ChatGPT-User','PerplexityBot','Claude-SearchBot'])ok(robots.includes(bot),`robots.txt missing ${bot}`);
for(const f of ['favicon.svg','favicon-48.png','favicon-96.png','favicon-192.png','favicon-512.png','favicon.ico','apple-touch-icon.png','og-image.png','404.php','site.webmanifest','llms.txt'])ok(fs.existsSync(path.join(pub,f)),`Missing ${f}`);
ok((sitemap.match(/<url>/g)||[]).length===10,'Sitemap count must be 10');ok((sitemap.match(/<lastmod>/g)||[]).length===10,'Every sitemap URL needs lastmod');ok(!fs.existsSync(path.join(pub,'ads.txt')),'ads.txt must not exist');
const banned=['adsbygoogle','googlesyndication','doubleclick','data-ad-slot','reCAPTCHA','turnstile'];for(const f of files.filter(f=>/\.(php|js|json|txt|md)$/i.test(f)&&f!==import.meta.filename)){const data=fs.readFileSync(f,'utf8').toLowerCase();for(const term of banned)ok(!data.includes(term.toLowerCase()),`${path.relative(root,f)} contains banned term ${term}`);}
ok(!fs.existsSync(path.join(root,'app_private/secrets.php')),'Real secrets.php must not be packaged');ok(fs.existsSync(path.join(root,'COPYRIGHT-SAFETY.md')),'Copyright safety file missing');ok(fs.existsSync(path.join(root,'EMAIL-SETUP.md')),'Email setup missing');
const settings=fs.readFileSync(path.join(pub,'settings.php'),'utf8');for(const token of ['OTHER','custom_currency_code','custom_currency_symbol','custom_currency_position','custom_currency_decimal_separator','custom_currency_thousands_separator','custom_currency_decimals'])ok(settings.includes(token),`Custom currency setting missing ${token}`);for(const token of ['currency_name','currency_symbol_position','currency_decimals','format_money'])ok(bootstrap.includes(token),`Currency engine missing ${token}`);
for(const token of ['country_currency_map','country_code','countryChoice'])ok(bootstrap.includes(token)||settings.includes(token),`Country auto-currency support missing ${token}`);const countryMapSection=bootstrap.match(/function country_currency_map\(\): array \{([\s\S]*?)\n\}/)?.[1]||'';ok((countryMapSection.match(/'[A-Z]{2}'\s*=>\s*'[A-Z]{3}'/g)||[]).length>=249,'Country-to-currency map must cover all countries and territories');
console.log(`${checks-failures.length}/${checks} checks passed`);if(failures.length){for(const f of failures)console.error(`FAIL: ${f}`);process.exit(1)}
